import "./globals.css";
import 'pliny/search/algolia.css'
import 'remark-github-blockquote-alert/alert.css'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SectionContainer from "@/components/common/SectionContainer";
import { SearchConfig, SearchProvider } from "pliny/search/index.js";
import siteMetadata from "@/config/siteMetadata";
import { ThemeProviders } from "./theme-providers";
import Header from "@/components/layouts/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white">
        <ThemeProviders>
        <SectionContainer>
            <SearchProvider searchConfig={siteMetadata.search as SearchConfig}>
              <Header />
              <main className="mb-auto">{children}</main>
            </SearchProvider>
            {/* <Footer /> */}
          </SectionContainer>
          </ThemeProviders>
      </body>
    </html>
  );
}
